name: CI

on: 
  push:
    branches:
    - dev_work

jobs:
  build:
    # ubuntu-latest, ubuntu-18.04, or ubuntu-16.04
    # windows-latest, windows-2019, or windows-2016
    # macOS-latest or macOS-10.14
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: checkout submodule
      run: git submodule sync --recursive && git submodule update --init --recursive
      
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
      continue-on-error: true # Allow steps to continue even with test failures

#     - name: Report
#       uses: asadmansr/android-test-report-action@master

    - name: build
      run: ./gradlew assembleDebug

#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
      
